# New SDSSRM-XCS Relations: Collating scatter dominating cluster names

This notebook uses the scatter-dominating galaxy cluster results from the jackknifing analysis of new SDSSRM-XCS scaling relations to produce tables and visualisations summarising which clusters were removed for each relation.

## Import Statements

In [7]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import numpy as np
from astropy.units import Quantity
from astropy.cosmology import LambdaCDM
import os

# This adds the directory above to the path, allowing me to import the common functions that I've written in
#  common.py - this just saves me repeating boring code and makes sure its all consistent
import sys
sys.path.insert(0, '..')
from common import xcs_cosmo, tx_norm, m_norm

## Loading data files

Important considerations for this dataset:
* The

### SDSSRM-XCS base sample

In [2]:
sdssxcs_base = pd.read_csv("../../sample_files/SDSSRM-XCS_base_sample.csv")
sdssxcs_base.head(6)

,name,MEM_MATCH_ID,xapa_ra,xapa_dec,rm_ra,rm_dec,z,r500,r500-,r500+,richness,richness_err,XCS_NAME,R_LAMBDA,xmm_targeted,xmm_serendipitous
0,SDSSXCS-124,124,0.80058,-6.09182,0.798261,-6.091694,0.2475,1181.028,21.202,23.203,109.550,4.490,XMMXCS J000312.1-060530.5,1.018410,True,False
1,SDSSXCS-2789,2789,0.95554,2.06802,0.956981,2.066469,0.1053,1007.861,17.194,17.202,38.904,2.830,XMMXCS J000349.3+020404.8,0.827942,True,False
2,SDSSXCS-290,290,2.72264,29.16102,2.714137,29.161154,0.3485,913.052,30.879,31.210,105.096,5.994,XMMXCS J001053.4+290939.6,1.009990,True,False
3,SDSSXCS-1018,1018,4.40633,-0.87619,4.406711,-0.878340,0.2144,902.259,22.445,23.366,56.997,3.219,XMMXCS J001737.5-005234.2,0.893655,False,True
4,SDSSXCS-134,134,4.90839,3.60982,4.911069,3.599257,0.2773,1123.321,19.219,19.226,108.604,4.792,XMMXCS J001938.0+033635.3,1.016645,True,False
5,SDSSXCS-119,119,8.46470,-7.86290,8.471426,-7.869543,0.3042,944.275,46.422,46.747,128.192,5.697,XMMXCS J003351.5-075146.4,1.050926,True,False

### SDSSRM-XCS scatter dominating clusters

#### Setting up path

In [8]:
sc_dom_res_path = "../../outputs/result_files/exploring_scatter/leave_one_jackknife/"

In [19]:
for rel_type in [n for n in os.listdir(sc_dom_res_path) if n[0] != '.']:
    cur_rel_path = os.path.join(sc_dom_res_path, rel_type)
    rel_sc_dom_files = [f for f in os.listdir(cur_rel_path) if f[0] != '.']

    for cur_sc_dom_file in rel_sc_dom_files:
        cur_sc_dom_file_path = os.path.join(cur_rel_path, cur_sc_dom_file)
        rel_data = pd.read_csv(cur_sc_dom_file_path)
        # At one point I made a mistake and was saving these result files with a useless 
        #  extra column, so we check for them, remove, and re-save the file here
        if 'Unnamed: 0' in rel_data.columns:
            rel_data = rel_data.drop(columns='Unnamed: 0')
            rel_data.to_csv(cur_sc_dom_file_path, index=False)
        print(rel_data)
        print('')
    stop

    dropped_cluster   slope  slope+-    norm  norm+-  scatter  scatter+-  \
0      SDSSXCS-1018  1.3929   0.0981  3.8375  0.1689   0.1559     0.0137
1     SDSSXCS-10401  1.3680   0.1007  3.8832  0.1727   0.1561     0.0137
2       SDSSXCS-110  1.3814   0.0977  3.8425  0.1688   0.1556     0.0137
3     SDSSXCS-11154  1.3867   0.0978  3.8659  0.1705   0.1567     0.0137
4      SDSSXCS-1131  1.3878   0.0974  3.8596  0.1689   0.1560     0.0136
..              ...     ...      ...     ...     ...      ...        ...
99      SDSSXCS-907  1.3817   0.0986  3.8505  0.1690   0.1565     0.0137
100    SDSSXCS-9258  1.3883   0.0994  3.8567  0.1714   0.1567     0.0137
101    SDSSXCS-9313  1.3974   0.0981  3.8356  0.1697   0.1562     0.0137
102     SDSSXCS-944  1.3938   0.0975  3.8346  0.1680   0.1557     0.0137
103    SDSSXCS-9803  1.3861   0.0980  3.8649  0.1711   0.1567     0.0138

     scatter_perc_change
0                 -0.023
1                  0.098
2                 -0.191
3                  0.526
4                  0.036
..                   ...
99                 0.357
100                0.495
101                0.203
102               -0.172
103                0.497

[104 rows x 8 columns]

    dropped_cluster   slope  slope+-    norm  norm+-  scatter  scatter+-  \
0      SDSSXCS-1018  1.3939   0.0964  3.8083  0.1669   0.1530     0.0135
1     SDSSXCS-10401  1.3699   0.0991  3.8527  0.1716   0.1533     0.0136
2       SDSSXCS-110  1.3838   0.0957  3.8076  0.1664   0.1520     0.0135
3     SDSSXCS-11154  1.3880   0.0966  3.8382  0.1697   0.1536     0.0136
4      SDSSXCS-1131  1.3896   0.0962  3.8286  0.1672   0.1531     0.0135
..              ...     ...      ...     ...     ...      ...        ...
99      SDSSXCS-907  1.3835   0.0970  3.8203  0.1671   0.1536     0.0135
100    SDSSXCS-9258  1.3899   0.0982  3.8259  0.1699   0.1538     0.0136
101    SDSSXCS-9313  1.3997   0.0969  3.8036  0.1678   0.1533     0.0135
102     SDSSXCS-944  1.3953   0.0958  3.8028  0.1663   0.1526     0.0135
103    SDSSXCS-9803  1.3881   0.0970  3.8328  0.1688   0.1539     0.0136

     scatter_perc_change
0                 -0.042
1                  0.117
2                 -0.717
3                  0.366
4                  0.036
..                   ...
99                 0.370
100                0.484
101                0.121
102               -0.291
103                0.551

[104 rows x 8 columns]

   dropped_cluster   slope  slope+-    norm  norm+-  scatter  scatter+-  \
0     SDSSXCS-1018  1.4293   0.0692  1.3140  0.0400   0.0932     0.0103
1    SDSSXCS-10401  1.4070   0.0707  1.3241  0.0407   0.0918     0.0101
2      SDSSXCS-110  1.4209   0.0680  1.3090  0.0390   0.0906     0.0101
3    SDSSXCS-11154  1.4272   0.0689  1.3167  0.0401   0.0927     0.0103
4     SDSSXCS-1131  1.4303   0.0691  1.3132  0.0399   0.0928     0.0102
..             ...     ...      ...     ...     ...      ...        ...
86     SDSSXCS-907  1.4324   0.0698  1.3133  0.0400   0.0933     0.0102
87    SDSSXCS-9258  1.4419   0.0698  1.3066  0.0399   0.0928     0.0101
88    SDSSXCS-9313  1.4264   0.0696  1.3161  0.0402   0.0929     0.0102
89     SDSSXCS-944  1.4238   0.0687  1.3192  0.0399   0.0919     0.0101
90    SDSSXCS-9803  1.4294   0.0695  1.3132  0.0403   0.0935     0.0102

    scatter_perc_change
0                 0.738
1                -0.815
2                -2.020
3                 0.236
4                 0.334
..                  ...
86                0.904
87                0.299
88                0.426
89               -0.671
90                1.035

[91 rows x 8 columns]

NameError: name 'stop' is not defined

In [3]:
pd.read_csv("/mtot-tx/mtot500_tx500_l1_jackknife_rel_pars.csv")

,Unnamed: 0,dropped_cluster,slope,slope+-,norm,norm+-,scatter,scatter+-,scatter_perc_change
0,0,SDSSXCS-1018,1.3929,0.0981,3.8375,0.1689,0.1559,0.0137,-0.023
1,1,SDSSXCS-10401,1.3680,0.1007,3.8832,0.1727,0.1561,0.0137,0.098
2,2,SDSSXCS-110,1.3814,0.0977,3.8425,0.1688,0.1556,0.0137,-0.191
3,3,SDSSXCS-11154,1.3867,0.0978,3.8659,0.1705,0.1567,0.0137,0.526
4,4,SDSSXCS-1131,1.3878,0.0974,3.8596,0.1689,0.1560,0.0136,0.036
...,...,...,...,...,...,...,...,...,...
99,99,SDSSXCS-907,1.3817,0.0986,3.8505,0.1690,0.1565,0.0137,0.357
100,100,SDSSXCS-9258,1.3883,0.0994,3.8567,0.1714,0.1567,0.0137,0.495
101,101,SDSSXCS-9313,1.3974,0.0981,3.8356,0.1697,0.1562,0.0137,0.203
102,102,SDSSXCS-944,1.3938,0.0975,3.8346,0.1680,0.1557,0.0137,-0.172
103,103,SDSSXCS-9803,1.3861,0.0980,3.8649,0.1711,0.1567,0.0138,0.497

### Combining tables

In [4]:
# sdssxcs_samp = pd.merge(sdssxcs_base, sdssxcs_txlx, left_on='name', right_on='name', how='outer')
# sdssxcs_samp = pd.merge(sdssxcs_samp, sdssxcs_mass, left_on='name', right_on='name', how='outer')

In [5]:
# sdssxcs_samp.columns